"""Seed catalog for categories, subcategories, and keyword rules."""

from __future__ import annotations

# (category_name, color, kind, description)
CATEGORY_SEED: list[tuple[str, str, str, str]] = [
    ("Comida", "#f97316", "expense", "Supermercado, restaurantes y delivery"),
    ("Transporte", "#3b82f6", "expense", "Movilidad y combustible"),
    ("Vivienda", "#8b5cf6", "expense", "Renta y servicios del hogar"),
    ("Salud", "#ef4444", "expense", "Farmacia y consultas"),
    ("Entretenimiento", "#ec4899", "expense", "Streaming, ocio y suscripciones"),
    ("Compras", "#14b8a6", "expense", "Ropa, electrónicos y misceláneos"),
    ("Deudas", "#64748b", "transfer", "Pagos a tarjetas y préstamos"),
    ("Transferencias", "#0ea5e9", "transfer", "SPEI y movimientos entre cuentas"),
    ("Ingresos", "#22c55e", "income", "Depósitos, nómina y reembolsos"),
]

# (subcategory_name, category_name)
SUBCATEGORY_SEED: list[tuple[str, str]] = [
    ("Super", "Comida"),
    ("Restaurante", "Comida"),
    ("Café", "Comida"),
    ("Delivery", "Comida"),
    ("Uber / DiDi viaje", "Transporte"),
    ("Gasolina", "Transporte"),
    ("Parking", "Transporte"),
    ("Transporte público", "Transporte"),
    ("Renta", "Vivienda"),
    ("Luz", "Vivienda"),
    ("Agua", "Vivienda"),
    ("Internet", "Vivienda"),
    ("Farmacia", "Salud"),
    ("Consulta médica", "Salud"),
    ("Streaming", "Entretenimiento"),
    ("Cine", "Entretenimiento"),
    ("Ropa", "Compras"),
    ("Electrónicos", "Compras"),
    ("Pago tarjeta", "Deudas"),
    ("Pago préstamo", "Deudas"),
    ("SPEI propio", "Transferencias"),
    ("Nómina", "Ingresos"),
    ("Reembolso", "Ingresos"),
]

# (pattern, match_type, category_name, subcategory_name, priority)
# Higher priority wins. Debt/transfer rules outrank generic merchant words.
RULE_SEED: list[tuple[str, str, str, str, int]] = [
    ("pago didi prestamos", "keyword", "Deudas", "Pago préstamo", 400),
    ("pago didi préstamos", "keyword", "Deudas", "Pago préstamo", 400),
    ("didi préstamos", "keyword", "Deudas", "Pago préstamo", 380),
    ("didi prestamos", "keyword", "Deudas", "Pago préstamo", 380),
    ("pago de rappicard", "keyword", "Deudas", "Pago tarjeta", 400),
    ("pago rappicard", "keyword", "Deudas", "Pago tarjeta", 400),
    ("pago tarjeta de credito nu", "keyword", "Deudas", "Pago tarjeta", 400),
    ("pago tarjeta de crédito nu", "keyword", "Deudas", "Pago tarjeta", 400),
    ("recibimos tu pago", "keyword", "Deudas", "Pago tarjeta", 350),
    ("pago de tarjeta", "keyword", "Deudas", "Pago tarjeta", 350),
    ("transferencia exitosa", "keyword", "Transferencias", "SPEI propio", 300),
    ("tu transferencia fue", "keyword", "Transferencias", "SPEI propio", 300),
    ("spei", "keyword", "Transferencias", "SPEI propio", 250),
    ("uber eats", "keyword", "Comida", "Delivery", 280),
    ("ubereats", "keyword", "Comida", "Delivery", 280),
    ("rappi", "keyword", "Comida", "Delivery", 200),
    ("didi food", "keyword", "Comida", "Delivery", 280),
    ("starbucks", "keyword", "Comida", "Café", 260),
    ("oxxo", "keyword", "Comida", "Super", 260),
    ("7-eleven", "keyword", "Comida", "Super", 260),
    ("seven eleven", "keyword", "Comida", "Super", 260),
    ("walmart", "keyword", "Comida", "Super", 260),
    ("soriana", "keyword", "Comida", "Super", 260),
    ("chedraui", "keyword", "Comida", "Super", 260),
    ("bodega aurrera", "keyword", "Comida", "Super", 260),
    ("costco", "keyword", "Comida", "Super", 260),
    ("uber", "keyword", "Transporte", "Uber / DiDi viaje", 180),
    ("didi", "keyword", "Transporte", "Uber / DiDi viaje", 160),
    ("pemex", "keyword", "Transporte", "Gasolina", 260),
    ("gasolinera", "keyword", "Transporte", "Gasolina", 260),
    ("cfe", "keyword", "Vivienda", "Luz", 260),
    ("telmex", "keyword", "Vivienda", "Internet", 260),
    ("izzi", "keyword", "Vivienda", "Internet", 260),
    ("totalplay", "keyword", "Vivienda", "Internet", 260),
    ("farmacia", "keyword", "Salud", "Farmacia", 240),
    ("farmacias del ahorro", "keyword", "Salud", "Farmacia", 260),
    ("similares", "keyword", "Salud", "Farmacia", 240),
    ("spotify", "keyword", "Entretenimiento", "Streaming", 260),
    ("netflix", "keyword", "Entretenimiento", "Streaming", 260),
    ("disney", "keyword", "Entretenimiento", "Streaming", 240),
    ("amazon prime", "keyword", "Entretenimiento", "Streaming", 260),
    ("cinepolis", "keyword", "Entretenimiento", "Cine", 260),
    ("cinemex", "keyword", "Entretenimiento", "Cine", 260),
    ("nomina", "keyword", "Ingresos", "Nómina", 260),
    ("nómina", "keyword", "Ingresos", "Nómina", 260),
    ("deposito", "keyword", "Ingresos", "Reembolso", 120),
    ("depósito", "keyword", "Ingresos", "Reembolso", 120),
    ("recibiste una transferencia", "keyword", "Ingresos", "Reembolso", 240),
]
